# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20161218202343) do

  create_table "active_admin_comments", force: :cascade do |t|
    t.string   "namespace"
    t.text     "body"
    t.string   "resource_id",   null: false
    t.string   "resource_type", null: false
    t.string   "author_type"
    t.integer  "author_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index ["author_type", "author_id"], name: "index_active_admin_comments_on_author_type_and_author_id"
    t.index ["namespace"], name: "index_active_admin_comments_on_namespace"
    t.index ["resource_type", "resource_id"], name: "index_active_admin_comments_on_resource_type_and_resource_id"
  end

  create_table "admin_users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
    t.index ["email"], name: "index_admin_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_admin_users_on_reset_password_token", unique: true
  end

  create_table "coordinators", force: :cascade do |t|
    t.string   "name"
    t.string   "email_address"
    t.string   "phone_number"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "photos", force: :cascade do |t|
    t.integer  "venue_id"
    t.string   "image_url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "ratings", force: :cascade do |t|
    t.integer  "venue_id"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "comment"
  end

  create_table "users", force: :cascade do |t|
    t.string   "email"
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.string   "password"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  create_table "venues", force: :cascade do |t|
    t.string   "address"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "website"
    t.integer  "capacity"
    t.string   "description"
    t.string   "drink_1"
    t.string   "drink_2"
    t.string   "drink_3"
    t.string   "drink_4"
    t.string   "drink_5"
    t.string   "food_1"
    t.string   "food_2"
    t.string   "food_3"
    t.string   "food_4"
    t.string   "food_5"
    t.integer  "drink_1_price"
    t.integer  "drink_2_price"
    t.integer  "drink_3_price"
    t.integer  "drink_4_price"
    t.integer  "drink_5_price"
    t.integer  "food_1_price"
    t.integer  "food_2_price"
    t.integer  "food_3_price"
    t.integer  "food_4_price"
    t.integer  "food_5_price"
    t.string   "amenity_1"
    t.string   "amenity_2"
    t.string   "amenity_3"
    t.string   "amenity_4"
    t.string   "amenity_5"
    t.string   "amenity_6"
    t.string   "amenity_7"
    t.string   "amenity_8"
    t.string   "rule_1"
    t.string   "rule_2"
    t.string   "rule_3"
    t.string   "rule_4"
    t.string   "rule_5"
    t.string   "rule_6"
    t.integer  "coordinator_id"
    t.string   "title"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "disclaimer"
    t.string   "rule_7"
    t.string   "rule_8"
    t.string   "rule_9"
    t.string   "rule_10"
    t.string   "dress_code_1"
    t.string   "dress_code_2"
    t.string   "dress_code_3"
    t.string   "dress_code_4"
    t.string   "dress_code_5"
    t.string   "dress_code_6"
    t.string   "dress_code_7"
    t.string   "dress_code_8"
    t.string   "dress_code_9"
    t.string   "dress_code_10"
    t.string   "dress_code_11"
    t.string   "dress_code_12"
    t.string   "dress_code_13"
    t.string   "dress_code_14"
    t.string   "dress_code_15"
    t.string   "dress_code_16"
    t.boolean  "private"
    t.boolean  "semiprivate"
    t.integer  "min_capacity"
    t.decimal  "state_sales_tax"
    t.decimal  "gratuity"
    t.string   "drink_1_desc"
    t.string   "drink_2_desc"
    t.string   "drink_3_desc"
    t.string   "drink_4_desc"
    t.string   "drink_5_desc"
    t.string   "food_1_desc"
    t.string   "food_2_desc"
    t.string   "food_3_desc"
    t.string   "food_4_desc"
    t.string   "food_5_desc"
    t.string   "food_6_desc"
    t.string   "food_7_desc"
    t.string   "food_8_desc"
    t.string   "food_9_desc"
    t.string   "food_10_desc"
    t.string   "food_11_desc"
    t.string   "food_12_desc"
    t.string   "food_13_desc"
    t.string   "food_14_desc"
    t.string   "food_15_desc"
    t.string   "food_16_desc"
    t.string   "food_17_desc"
    t.string   "food_18_desc"
    t.string   "food_19_desc"
    t.string   "food_20_desc"
    t.string   "food_21_desc"
    t.string   "food_22_desc"
    t.string   "food_23_desc"
    t.string   "food_24_desc"
    t.string   "food_25_desc"
    t.string   "food_26_desc"
    t.string   "food_27_desc"
    t.string   "food_28_desc"
    t.string   "food_29_desc"
    t.string   "food_30_desc"
    t.string   "food_31_desc"
    t.string   "food_32_desc"
    t.string   "food_33_desc"
    t.string   "food_34_desc"
    t.string   "food_35_desc"
    t.string   "food_36_desc"
    t.string   "food_37_desc"
    t.string   "food_38_desc"
    t.string   "food_39_desc"
    t.string   "food_40_desc"
    t.string   "food_6"
    t.string   "food_7"
    t.string   "food_8"
    t.string   "food_9"
    t.string   "food_10"
    t.string   "food_11"
    t.string   "food_12"
    t.string   "food_13"
    t.string   "food_14"
    t.string   "food_15"
    t.string   "food_16"
    t.string   "food_17"
    t.string   "food_18"
    t.string   "food_19"
    t.string   "food_20"
    t.string   "food_21"
    t.string   "food_22"
    t.string   "food_23"
    t.string   "food_24"
    t.string   "food_25"
    t.string   "food_26"
    t.string   "food_27"
    t.string   "food_28"
    t.string   "food_29"
    t.string   "food_30"
    t.string   "food_31"
    t.string   "food_32"
    t.string   "food_33"
    t.string   "food_34"
    t.string   "food_35"
    t.string   "food_36"
    t.string   "food_37"
    t.string   "food_38"
    t.string   "food_39"
    t.string   "food_40"
    t.integer  "food_6_price"
    t.integer  "food_7_price"
    t.integer  "food_8_price"
    t.integer  "food_9_price"
    t.integer  "food_10_price"
    t.integer  "food_11_price"
    t.integer  "food_12_price"
    t.integer  "food_13_price"
    t.integer  "food_14_price"
    t.integer  "food_15_price"
    t.integer  "food_16_price"
    t.integer  "food_17_price"
    t.integer  "food_18_price"
    t.integer  "food_19_price"
    t.integer  "food_20_price"
    t.integer  "food_21_price"
    t.integer  "food_22_price"
    t.integer  "food_23_price"
    t.integer  "food_24_price"
    t.integer  "food_25_price"
    t.integer  "food_26_price"
    t.integer  "food_27_price"
    t.integer  "food_28_price"
    t.integer  "food_29_price"
    t.integer  "food_30_price"
    t.integer  "food_31_price"
    t.integer  "food_32_price"
    t.integer  "food_33_price"
    t.integer  "food_34_price"
    t.integer  "food_35_price"
    t.integer  "food_36_price"
    t.integer  "food_37_price"
    t.integer  "food_38_price"
    t.integer  "food_39_price"
    t.integer  "food_40_price"
  end

end
